version = 0.1
[default.deploy.parameters]
stack_name = "golang-updatetokenservico"
resolve_s3 = false
s3_prefix = "golang-updatetokenservico"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
